name: build-pyjq

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build standalone pyjq
        run: |
          pyinstaller --onefile --name pyjq compiler/jq_cli.py

      - name: Rename artifact
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            windows-latest)
              mv dist/pyjq.exe pyjq-windows.exe
              ;;
            ubuntu-latest)
              mv dist/pyjq pyjq-linux
              ;;
            macos-latest)
              mv dist/pyjq pyjq-macos
              ;;
          esac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyjq-${{ matrix.os }}
          path: pyjq-*
